### ISSUE TITLE
Skipped tests display

### ISSUE THREAD

**Issue by tbruyelle** [rakyll/gotest#13]
If the main test is PASS, SKIP appears as PASS, otherwise it appears as FAIL:

![Screenshot from 2019-04-09 17-09-34](https://user-images.githubusercontent.com/92280/55811943-4ea82400-5aea-11e9-8906-be600039c516.png)
![Screenshot from 2019-04-09 17-09-45](https://user-images.githubusercontent.com/92280/55811956-510a7e00-5aea-11e9-879e-5e292a09d4a3.png)

Is this intentional ?

**Comment by subtlepseudonym** [comment]
This is likely due to color leakage into lines that should be the default terminal text color. This is fixed in #10
