### ISSUE TITLE
Using ANSI colours instead

### ISSUE THREAD

**Issue by bentcoder** [rakyll/gotest#20]
Hi,

Just wondering what you would say if I proposed to use ANSI colours for output instead of "github.com/fatih/color". If you used ANSI (e.g. `fmt.Println("\033[1;44mSOME TEXT GOES HERE\033[0m")`), output colours wouldn't be lost as opposed to the current situation. Example below won't print the colours anymore - neither in terminal nor in IDE.

Thanks

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os/exec"
)

func main() {
	cmd := exec.Command("gotest", "-v", "./...")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatal(err)
	}
	_ = cmd.Start()

	buffer := bufio.NewReader(stdout)

	for {
		line, _, err := buffer.ReadLine()

		fmt.Println(string(line))

		if err == io.EOF {
			break
		}
	}
}
```

**Comment by mattLLVW** [comment]
you can use `CI=true` to force ansi color
