### ISSUE TITLE
Introduce a colorblind flag

### ISSUE THREAD

**Issue by crossi36** [rakyll/gotest#3]
We talked about this briefly on [Twitter](https://twitter.com/crossi36/status/910878238095872006), but I thought it would be a good idea to move the discussion to a place where messages can be a bit longer.

I did some research and found the following:
Essentially, there are 5 different types of color vision deficiencies with varying degrees of severity.

1. Red-weak/blind
2. Green-weak/blind
3. Blue-weak/blind
4. Blue Cone Monochromacy
5. Monochromacy

I found [this simulator](http://www.color-blindness.com/coblis-color-blindness-simulator/). I don't know how accurate it is, but I think (hope) that it gives us at least an idea of what the output might look like for the different types.

Type 1 and 2 obviously have the biggest issue. 

Type 3 seems to be fine, although the green looses some saturation. 

Type 4 losses a lot of saturation. From what I've read they only have blue cones, which led me to believe that they should see blue just fine, but in the simulator it looks like they loose saturation across all colors, which might make it tricky.

Type 5 sees no color at all, although they seem to see different shades of white/grey/black, so only coloring errors might help them, too.

All in all I think [your suggested color scheme](https://twitter.com/rakyll/status/910935318207049729) (blue for errors, standard color for the rest) is a step in the right direction. Blue seems to be working relatively well where green and red are not. 

An alternative approach might be to let users pick their own colors. This way they could figure out colors that work for them, while green/red can work as the somewhat expected default.

**Comment by rakyll** [comment]
I was wondering whether we can support a grayscale output. It might only highlight the errors and leave everything else dim. But the better solution would be having an env variable to allow users to set their color theme. It also works for other users who are not happy with the color coloring scheme, especially if it is not working well with their terminal theme.

**Comment by crossi36** [comment]
It seems like there are only a handful of colors to choose from (judging by github.com/fatih/color, never really thought about colored terminal output before this). I thought that maybe the desired "greyscale" effect could be achieved by printing the errors in bold, but I feel like the difference is almost negligible (especially on dark background). What do you think?

![example](https://user-images.githubusercontent.com/12022001/30826993-da7ab338-a238-11e7-9d61-608cb9675ef0.png)

**Comment by rakyll** [comment]
Depends on the font but I find it hard to distinguish the bold myself on dark background. Let's add a palette option instead, "GOTEST_PALETTE=green,red" to be the default option.
