### ISSUE TITLE
doesn't support 1.18.x ?

### ISSUE THREAD

**Issue by lkeix** [rakyll/gotest#45]
Hi

I used gotest on goenv 1.18.
I can't run gotest command after `go get -u github.com/rakyll/gotest`.

If I can run gotest command, run below command.

```:bash
mkdir $GOPATH/bin
cd $GOPATH/pkg/mod/github.com/rakyll/gotest@v0.0.6
go build -o gotest main.go
mv gotest $GOPATH/bin
```

**Comment by Jose-Francisco-neto** [comment]
use `go install` instead of `go get -u`

See: https://go.dev/doc/go-get-install-deprecation
